### ISSUE TITLE
Setup Stage and Demo servers

### ISSUE THREAD

**Issue by anjhero** [younginnovations/UN-Transparency-Portal#1]
We need to setup two servers: Stage and Demo

- **Stage** - This will be used as a stable server.  
- **Demo** - This will be used as a working server. This may contain unstable changes and will be used to track day-to-day updates.

**Comment by bezunakarmi** [comment]
Deployment is now ready for both stage and demo server. We can deploy with the following commands 
- For Demo Server : <br />
   cap demo deploy user={username} branch={branchName} port=8082 <br />
   Eg : cap demo deploy user=biju branch=UNTP-1 port=8082
- For Stage Server : <br />
   cap staging deploy user={username} branch={branchName} port=8081<br />
   Eg : cap staging deploy user=biju branch=UNTP-1 port=8081
