### ISSUE TITLE
Provide Icons/ logo of UN agencies

### ISSUE THREAD

**Issue by anjhero** [younginnovations/UN-Transparency-Portal#11]

**Comment by anjesh** [comment]
Provide icons of all the UN agencies, provide links to their transparency portal (if available) and links to their websites. 

Please clarify on linking of these logos. Do you mean that these logos are out-linked to either their transparency portal or their website? In this case, the people will go out of our portal even if these agencies have page in our portal.

**Comment by anjhero** [comment]
please provide update on this @abdulriza

**Comment by abdulriza** [comment]
@anjesh As we discussed the homepage links will be directed to the organization's page within the portal and we will have the links to the respective individual transparency portals on the organization's page.

**Comment by anjhero** [comment]
@abdulriza yes, that is how it works right now in the demo page. However, we require the logo of each agency in vector format.

**Comment by anjesh** [comment]
Logos received https://drive.google.com/a/yipl.com.np/folderview?id=0BwoAm3ycE5n2Y2RyTXRuTUJoOWs&usp=sharing#
