### ISSUE TITLE
Listing of countries - all countries or just countries with UN agencies

### ISSUE THREAD

**Issue by anjhero** [younginnovations/UN-Transparency-Portal#12]
Should we list all countries or just countries where UN agencies are located? Listing all countries (regardless of them having UN agencies or not) will give an overview of which countries do not have a UN agency.

**Comment by anjesh** [comment]
As per discussion with the UNDG team, we will only have the countries that have activities published by UN agencies. We will not be showing the countries with empty activities. @abdulriza

**Comment by abdulriza** [comment]
@anjesh Agreed. The list of countries will be decided by the existing countries in the UN agencies' data set.
