### ISSUE TITLE
setup open.undg.org domain

### ISSUE THREAD

**Issue by anjesh** [younginnovations/UN-Transparency-Portal#125]
Need to setup open.undg.org for the launch @mariablancolora

**Comment by mariablancolora** [comment]
Kindly let me know what do you need so I can discuss it with the IT person. Thanks!!

**Comment by anjesh** [comment]
You need to create the subdomain open.undg.org and point the A record to this ip: 188.166.155.208 
We will do the necessary setup in this server to run the system in port 80

**Comment by mariablancolora** [comment]
Done! Thanks!!!

**Comment by anjesh** [comment]
"A" record is not yet reflected for open.undg.org. It will work once 188.166.155.208 appears in A record in dig. 

![image](https://cloud.githubusercontent.com/assets/120488/15698315/0c7a04d2-27e3-11e6-824f-68a542a730fc.png)

**Comment by anjesh** [comment]
working now.
