### ISSUE TITLE
Homepage and individual agency page totals do not match

### ISSUE THREAD

**Issue by abdulriza** [younginnovations/UN-Transparency-Portal#132]
@anjesh @bezunakarmi The stats box on homepage is showing the following figures for budget and expenditure;
Total budget  - 519, 429 M
Total expenditure – 64, 485 M

In order to validate I simply added the total budget and expenditure amounts showing on individual agency pages and following is the table;

![total](https://cloud.githubusercontent.com/assets/3297817/15726573/97463fea-281f-11e6-88e4-c4347731b400.png)
 
You can clearly see the difference of the homepage, especially on expenditure. I am disappointed to see that you have not validate this yet, after all I keep saying that the total on home page is wrong. Could you please check and fix urgently.

**Comment by bezunakarmi** [comment]
this has been solved.
