### ISSUE TITLE
Data text change on each pages

### ISSUE THREAD

**Issue by abdulriza** [younginnovations/UN-Transparency-Portal#136]
@anjesh @bezunakarmi The text box on the bottom of every pages to explain the data need to be changed according to the changes we have made. Please replace the existing text with the following accordingly; 

- **Home page :** 

    Where is the data from?

   Data in the dropdown menu is built from the database which updates everyday at GMT +0 with 
   new    data fetched from the IATI Registry.

  The list of publishers comes from published XML activities reported by UNDG members in the IATI     Registry database.

  We list countries that are reported by publishers using ISO3166 Alpha-2. 

  The dropdown list of sectors corresponds to OECD DAC 3 Digit sector codes.

- **Agency, country and sector pages:**
  
   How is the data calculated?

   The data sources on this page are:

   Where does the money come from?
   IATI data for 2015 taken from the IATI Registry each night.

   Where does the money go? (Sectors)
   IATI data for 2015 taken from the IATI Registry each night. Sector classification corresponds to    OECD DAC CRS 5 Digit sector codes.

   Heatmap
   A count of IATI activities that contain specific coordinates in their location data. NB - very few IATI  activities currently contain this data.

   Typically this data will have been updated from the IATI Registry everyday at midnight GMT.

- **'About data quality' page :** http://www.open.undg.org/ctrack.html?publisher=41119&tongue=eng#view=data_quality

   The data currently available in UNDG portal comes from United Nations agencies who are  publishing their development activities in IATI-XML format. This data is published on their own websites and indexed on IATI's Registry. On a nightly basis IATI pulls all data indexed on the registry and saves the latest version of each published activity in a central Datastore. The Datastore is therefore not a curated database, but a compilation of all IATI data as of last night.

   The IATI standard is flexible in its reporting rules to allow as many different organisations with varying capacity to publish their data in this common format. The philosophy is for organisations to start publishing what they can and improve the quality of their data over time. This means that there will always be data of varying quality available through IATI.

   However, IATI was established to meet the needs of developing countries, who have consistently asked for timely, comprehensive and forward-looking information that can be used in the planning and monitoring of development.A recent survey conducted by IATI reinforced these demands. IATI's ask is therefore that publishers update their data at least quarterly; that the latest data is not more than three months out of date; and that forward-looking activity-level budgets are provided for at least one year in advance.

   This portal showcases the best practice of a number of UN agencies. However, there are agencies currently not meeting what developing countries have clearly indicated as their minimum requirements. We have attempted to show where data is missing and where it is present. In various tables you will see cells containing "0" which may indicate areas where IATI publishers are failing to provide any data, or provide low quality data which cannot currently be shown in UNDG portal. 

   We hope that our presentation of the data - and the current gaps - provides a useful overview of the data landscape. Where there are critical gaps in the data we would encourage you to engage with us to identify and improve the quality of data currently available.

**Comment by bezunakarmi** [comment]
This has been done.Please do check.
