### ISSUE TITLE
Active project number is wrong for UN Women

### ISSUE THREAD

**Issue by abdulriza** [younginnovations/UN-Transparency-Portal#140]
@anjesh @bezunakarmi The active project number on UN Women page is showing wrongly as zero instead of 20. Could you please check and fix it urgently.

http://www.open.undg.org/ctrack.html?publisher=411124&tongue=eng#view=publisher

**Comment by abdulriza** [comment]
@anjesh @bezunakarmi dont worry about it. I checked and the issue is with the use of activity dates wrongly. Anyways I am keeping this issue open as I need to discuss something related to the dates.

**Comment by anjesh** [comment]
Please reopen if there's anything.
