### ISSUE TITLE
IATI budget total is not showing up on the table for WFP

### ISSUE THREAD

**Issue by abdulriza** [younginnovations/UN-Transparency-Portal#141]
@bezunakarmi @anjesh WFP table is showing zero for 'total' budget column. 
http://www.open.undg.org/ctrack.html?publisher=XM-DAC-41140&tongue=eng#view=publisher_countries&year=2015

This information should be coming from Organization xml and WFP is publishing xml org file.

http://cdn.wfp.org/iati/organizations.xml

**Comment by bezunakarmi** [comment]
The total budget for total budget has been listed.Please do check.
