### ISSUE TITLE
Issue with expenditure on country table for Global and regional - Organization page

### ISSUE THREAD

**Issue by abdulriza** [younginnovations/UN-Transparency-Portal#146]
@anjesh @bezunakarmi On the organization page country table, when you click on the year label it keeps increasing the expenditure amount for global and regional. It supposed to change the order of countries (ascending or descending) not to change any amount in the table.

**Comment by abdulriza** [comment]
@anjesh @bezunakarmi Forgot to mention the issue of expenditure amount for ILO. It looks like the original amount shown is also wrong. For ILO, the amount for global amount for 2013 should be USD 110,357,633 whereas the UNDG portal is showing 331,072,899. This is exactly 3 times of the amount. I guess for some reason the script calculation is tripling the original amount.

**Comment by bezunakarmi** [comment]
@abdulriza the following issues has been solved. Please do check.
