### ISSUE TITLE
Compare all agencies table numbers look wrong 

### ISSUE THREAD

**Issue by abdulriza** [younginnovations/UN-Transparency-Portal#150]
@bezunakarmi @anjesh The amount shown on compare all table looks wrong http://open.undg.org/ctrack.html?tongue=eng#view=publishers. I checked the figures for UNDP - The amount for 2016 UNDP expenditure should be USD 1,448,412,190 whereas the portal shows 1,339,382,633. Also the budget for 2016 should be 5,001,516,156 whereas portal shows 4,578,868,171. 

Last time we checked and I guess we confirmed all numbers look good. Now looking at the difference raising the concerns again. Could you urgently look into this?

**Comment by bezunakarmi** [comment]
@abdulriza We cross checked the data with d-portal.org and downloaded the budget csv file for UNDP and found that our calculation results as same as shown in open.undp.org. However we couldn't match it with the data found on http://dashboard.iatistandard.org/publisher/undp.html.

We will look further into it and have you updated on this as soon as possible.

**Comment by anjesh** [comment]
Should have been taken care of by now.
