### ISSUE TITLE
Show the text when hovering over "Total UN Budget" section

### ISSUE THREAD

**Issue by anjesh** [younginnovations/UN-Transparency-Portal#152]
We need to show this following information in the second box "Total UN budget" through either hover over text or with the use of icon

> These figures include budget data ever published in IATI by all UN members and observers (including The World Bank and UN OCHA) 

Thoughts on how to? @anjhero

**Comment by bezunakarmi** [comment]
@anjesh this has been done and deployed. Please do have a look.

**Comment by mariablancolora** [comment]
This is the text that should go:
**Total UN budget includes all data ever published in IATI by all UN members and observers (including The World Bank).**
The hover over doesn't work in mobile (iphone 5, iphone 6, iphone 6 plus), and unfortunately this is necessary for us. So we would like to propose to move the text underneath the blue tiles, on the white space. Could you kindly arrange this? Thanks for your help.

**Comment by bezunakarmi** [comment]
This issue has been solved. Please do check.
