### ISSUE TITLE
New logo on the transparency portal

### ISSUE THREAD

**Issue by mariablancolora** [younginnovations/UN-Transparency-Portal#153]
Hi! Would it be possible to update the logo in the transparency portal? We would need to replace the UNDG logo with the new version of it. Please let me know if the file attached works. You can change it to white. Thanks!!

**Comment by anjesh** [comment]
There's no attachment. @mariablancolora

**Comment by mariablancolora** [comment]
Here it is!

Best,

Maria

________________________________
De: Anjesh <notifications@github.com>
Enviado: lunes, 30 de enero de 2017 10:47:43
Para: younginnovations/UN-Transparency-Portal
Cc: Maria Blanco; Mention
Asunto: Re: [younginnovations/UN-Transparency-Portal] New logo on the transparency portal (#153)


There's no attachment. @mariablancolora<https://github.com/mariablancolora>

-

**Comment by bezunakarmi** [comment]
The logo has been changed. Please do have a look.
![screen shot 2017-02-03 at 3 21 28 pm](https://cloud.githubusercontent.com/assets/12218329/22586402/a124a926-ea24-11e6-90e9-bd36f6065a88.png)
