### ISSUE TITLE
Add UNAIDS data to the portal

### ISSUE THREAD

**Issue by abdulriza** [younginnovations/UN-Transparency-Portal#154]
@anjesh @anjhero @bezunakarmi  UNAIDS has started publishing to IATI since last November. We need to add UNAIDS to the list to extract the data and activate it on the list. 

https://iatiregistry.org/publisher/unaids

**Comment by bezunakarmi** [comment]
UNAIDS has been added to the portal. Please do have a look at : http://open.undg.org/ctrack.html?publisher=XM-DAC-41110&tongue=eng#view=publisher
![screen shot 2017-02-14 at 2 14 24 pm](https://cloud.githubusercontent.com/assets/12218329/22921006/03a8f31a-f2c0-11e6-9723-87b2751f6bb5.png)
