### ISSUE TITLE
New link on main menu (top banner)

### ISSUE THREAD

**Issue by mariablancolora** [younginnovations/UN-Transparency-Portal#155]
Dear Anjesh, 

Could you kindly add another item to the menu on the top banner of the portal? 

The text to add is **Data Visualization Contest**. 

This text should be link directly to the following webpage: 
https://undg.org/undg-data-visualization-contest/ 

Could you add it after Feedback?

Could you add it in bold so it would stand out from the rest of the menu? We would need this to be implemented on the 17th of February, not before that. 

Thanks!!

**Comment by anjesh** [comment]
Sure @mariablancolora, will get it live on 17th.

**Comment by mariablancolora** [comment]
Thanks Anjesh!!

________________________________
De: Anjesh <notifications@github.com>
Enviado: martes, 14 de febrero de 2017 0:31:50
Para: younginnovations/UN-Transparency-Portal
Cc: Maria Blanco; Mention
Asunto: Re: [younginnovations/UN-Transparency-Portal] New link on main menu (top banner) (#155)


Sure @mariablancolora<https://github.com/mariablancolora>, will get it live on 17th.

**Comment by anjesh** [comment]
Added

![image](https://cloud.githubusercontent.com/assets/120488/23169690/dca60a22-f874-11e6-8804-1bf61011306a.png)
