### ISSUE TITLE
Prepare XML file dump of all the agencies for the viz contest

### ISSUE THREAD

**Issue by anjesh** [younginnovations/UN-Transparency-Portal#158]
The XML files of a given agency should be placed in a folder named agency-name. If unicef has 10 xml files, then there should be a folder "unicef" and should contain 10 xml files. 
```
xmldump
    -- unicef 
         -- file1.xml
         -- file2.xml
         -- .....
         -- file10.xml
    -- unaids
         -- file1.xml
         -- file2.xml
         -- .....
         -- file10.xml
```

**Comment by bezunakarmi** [comment]
You can download XML of all the UN Agencies publishing in IATI from [here](http://open.undg.org/data.tar.gz). 

Please have a look. If its good you can close the issue.

**Comment by anjesh** [comment]
Looks good :)
