### ISSUE TITLE
Country page design/ mockup 

### ISSUE THREAD

**Issue by anjhero** [younginnovations/UN-Transparency-Portal#16]
Country page will have following:
- Stats summary (termed as Currently published in IATI) at the top of the page (including Total active projects, Total ended projects, Total projects, Total Budget, Total budget, Total expenditure)
- Where does the money come from - Display all UN agencies (and not just 4)
- Where does the money come from - Should include the amount of other organisations total and % to show the comparison UN organisations vs others. 
- Other contents to remain same as in the current D-portal country page.

**Comment by abdulriza** [comment]
@anjhero @anjesh In making the visualization for 'where does the money come from' we will have to be bit creative as listing all agencies in the chart (the way it is now shown on d-portal) will look bit messy. The use of tooltips or legends can be considered to provide a clean visualization.

**Comment by anjhero** [comment]
This is reflected in other issues. I'm closing this issue
