### ISSUE TITLE
link to XML dump file broken

### ISSUE THREAD

**Issue by crazysquib** [younginnovations/UN-Transparency-Portal#162]
hey, the link to the .gz file seems to be inactive: 

http://open.undg.org/data.tar.gz

getting 'no file found'.

**Comment by anjesh** [comment]
Thanks for the info. Could you try now? The link is working.

**Comment by crazysquib** [comment]
hey, still not working for me.  tried two different browsers.

**Comment by anjesh** [comment]
Please try once again. It's working now.

**Comment by crazysquib** [comment]
yes indeed, it works now.  thank you very much.
