### ISSUE TITLE
Update UNCDF logo

### ISSUE THREAD

**Issue by anjesh** [younginnovations/UN-Transparency-Portal#163]
Replace the existing UNCDF logo with this one. 
![uncdf](https://cloud.githubusercontent.com/assets/120488/25262166/ff12dcb4-2675-11e7-990c-65a2b85b67e5.png)

**Comment by bezunakarmi** [comment]
This has been done. Have a look.

![screen shot 2017-04-24 at 1 39 27 pm](https://cloud.githubusercontent.com/assets/12218329/25327335/7a766040-28f3-11e7-8ea0-68576ae94bbc.png)

![screen shot 2017-04-24 at 1 39 10 pm](https://cloud.githubusercontent.com/assets/12218329/25327336/7b570866-28f3-11e7-81af-e40e7f5c99fa.png)

**Comment by anjesh** [comment]
@abdulriza @mariablancolora logo updated.

**Comment by mariablancolora** [comment]
Thanks Anjesh!

________________________________
De: Anjesh <notifications@github.com>
Enviado: lunes, 24 de abril de 2017 5:48:37
Para: younginnovations/UN-Transparency-Portal
Cc: Maria Blanco; Mention
Asunto: Re: [younginnovations/UN-Transparency-Portal] Update UNCDF logo (#163)


@abdulriza<https://github.com/abdulriza> @mariablancolora<https://github.com/mariablancolora> logo updated.

**Comment by anjesh** [comment]
@bezunakarmi shall we replace the png with svg for better clarity? Lets try and see if this gives more clear/crisp text in the logo than the current one. 

[UNCDF.svg.zip](https://github.com/younginnovations/UN-Transparency-Portal/files/957284/UNCDF.svg.zip)

**Comment by anjesh** [comment]
@bezunakarmi please close this once you are done.

**Comment by bezunakarmi** [comment]
Logo for UNCDF has been changed from png to svg. But all other publishers logo are in png. Please reopen this issue, if needed to be rolled back.
