### ISSUE TITLE
Incoming commitment is not displayed on open.undg.org   

### ISSUE THREAD

**Issue by abdulriza** [younginnovations/UN-Transparency-Portal#166]
@anjesh @bezunakarmi In IATI standard transaction type code "11" refers to "Incoming Commitment". On the activity page transaction type description is showing 11 instead of incoming commitment. I guess code 11 is not included in the existing codes. Could you please check and fix urgently.  

example: http://open.undg.org/ctrack.html?publisher=XM-DAC-41114&tongue=eng#view=act&aid=XM-DAC-41114-OUTPUT-00048778

**Comment by bezunakarmi** [comment]
This has been solved.
![screen shot 2017-04-25 at 10 55 48 am](https://cloud.githubusercontent.com/assets/12218329/25369742/df92635e-29a5-11e7-8ed2-a0b32f56bd7c.png)
