### ISSUE TITLE
Change of text on UN agencies not publishing to IATI

### ISSUE THREAD

**Issue by abdulriza** [younginnovations/UN-Transparency-Portal#167]
@anjesh @anjhero Currently we are displaying a message 'Not an IATI Publisher" when someone hover over the logo of agencies not publishing to IATI. Can we change it to 'Not yet publishing'. This is to show the correct message because some of the agencies are already an IATI signatory (so literally they are IATI publishers) but just haven't started to publish the data yet. 

Also can we change the title 'UN agencies in IATI' in the box showing the total number (16) of UN agencies publishing to 'UN publishers'. 

Since there is a tweet relating to the joining of the IOM to IATI, I would appreciate if we can make this change ASAP. We also need to include IOM to the list and I will share the logo soon.

**Comment by anjesh** [comment]
[ ] Change hover-msg "Not an IATI Publisher" to "Not yet publishing" in the homepage UNDG members list.
[ ]  Change "UN agencies in IATI" to "UN Publishers" in homepage

See https://github.com/younginnovations/UN-Transparency-Portal/issues/168 for IOM logo enable.

**Comment by bezunakarmi** [comment]
This has been done. Please have a look.

![screen shot 2017-05-08 at 3 18 59 pm](https://cloud.githubusercontent.com/assets/12218329/25798646/b0dfaf60-3401-11e7-835b-7e3a32455066.png)

![screen shot 2017-05-08 at 3 08 28 pm](https://cloud.githubusercontent.com/assets/12218329/25798306/565f751c-3400-11e7-8947-0449ae3891a3.png)
