### ISSUE TITLE
Show IOM logo in the UNDG member's list

### ISSUE THREAD

**Issue by anjesh** [younginnovations/UN-Transparency-Portal#168]
IOM is not yet IATI publisher, so they just need to appear in the homepage list. 
[OIM-IOM.eps.zip](https://github.com/younginnovations/UN-Transparency-Portal/files/982685/OIM-IOM.eps.zip)

**Comment by abdulriza** [comment]
I guess IOM is now added to the list but the logo is not visible at all. Can you check?

**Comment by bezunakarmi** [comment]
IOM has been added. Please do have a look.
![screen shot 2017-05-09 at 10 50 22 am](https://cloud.githubusercontent.com/assets/12218329/25836318/749b99a2-34a5-11e7-9c26-0aa4affaf16b.png)
