### ISSUE TITLE
UNCDF sector data is not available on the portal

### ISSUE THREAD

**Issue by abdulriza** [younginnovations/UN-Transparency-Portal#170]
@anjesh @bezunakarmi UNCDF now publish DAC-3 sector codes in their xml but the data is not picked under 'funding went to sectors'. I had a quick look and the xml sector codes look fine. Can you check?

Thanks.

**Comment by anjesh** [comment]
UNCDF XML is using version 1.3 with 3 Digit sector codes and hence d-portal existing code doesn't scrape the sector vocab DAC-3 as can be seen here https://github.com/younginnovations/UN-Transparency-Portal/blob/master/dstore/js/dstore_db.js#L584. We will fix this in our codebase for now.

**Comment by bezunakarmi** [comment]
The issue has been solved by making necessary changed as mentioned above.
![screen shot 2017-05-11 at 9 09 26 pm](https://cloud.githubusercontent.com/assets/12218329/25957514/3b6ae9d6-368e-11e7-97f1-7ef60f1b8b6a.png)
