### ISSUE TITLE
Add FAO data to the portal

### ISSUE THREAD

**Issue by abdulriza** [younginnovations/UN-Transparency-Portal#171]
@anjesh @bezunakarmi FAO started publishing to IATI from this month. Can we start fetching FAO data to the portal.  

https://iatiregistry.org/publisher/fao

**Comment by bezunakarmi** [comment]
FAO has been added as UN publishers for IATI.
![screen shot 2017-05-22 at 12 00 39 pm](https://cloud.githubusercontent.com/assets/12218329/26294855/7f67b6b8-3ee6-11e7-9888-209fc33005eb.png)
![screen shot 2017-05-22 at 12 00 31 pm](https://cloud.githubusercontent.com/assets/12218329/26294856/8144a266-3ee6-11e7-8828-15eb7f9ea0fb.png)
