### ISSUE TITLE
Something is not right with countries

### ISSUE THREAD

**Issue by abdulriza** [younginnovations/UN-Transparency-Portal#175]
@bezunakarmi @anjesh I feel something is not right with the portal. I just noticed that the country list on the home page is not shown properly and some country pages are not loading up (eg. Nepal, Tanzania). Could you please have a look.

**Comment by bezunakarmi** [comment]
@abdulriza Missing flags for countries has been added. Also, the data not showing issue with country detail page has been fixed.
