### ISSUE TITLE
UNICEF data missing in the portal

### ISSUE THREAD

**Issue by anjesh** [younginnovations/UN-Transparency-Portal#178]
http://open.undg.org/ctrack.html?country=BO&tongue=eng#view=main

![image](https://user-images.githubusercontent.com/120488/31110545-866b652c-a827-11e7-825c-436d7ee0942a.png)

**Comment by bezunakarmi** [comment]
<img width="1209" alt="screen shot 2017-10-03 at 5 35 01 pm" src="https://user-images.githubusercontent.com/12218329/31123805-380b2c70-a861-11e7-9748-293db05fa7e9.png">
