### ISSUE TITLE
Showing Recipient Region

### ISSUE THREAD

**Issue by anjesh** [younginnovations/UN-Transparency-Portal#180]
- [x] do quick analysis of all the activities and see how many different regions are mentioned
- [x] identify the way to present region page (similar to country page?)
- [x] these regions should be listed alongside country list in the home page (after all the countries are listed?)

Currently all the “recipient region” is grouped as a single entry in the listing as “Regional and global”. It was discussed that the disaggregated figure would be more useful in the list.

**Comment by anjesh** [comment]
Quick analysis of the data shows that the following codes are mentioned in the recipient-region element in UN Activities XML files. 

All the mentioned invalid codes will be mapped to Global-Regional page whereas [valid region-codes](http://iatistandard.org/201/codelists/Region/) will have their own page.

```
"global-regional": {
	"89": "89",
	"679": "679",
	"889": "889",
	"GLOBAL": "GLOBAL",
	"GZ": "GZ",
	"KO": "KO",
	"REG-ARAB-STATES": "REG-ARAB-STATES",
	"REG-ASIA-PACIFIC": "REG-ASIA-PACIFIC",
	"REG-EASTERN-SOUTHERN-AFRICA": "REG-EASTERN-SOUTHERN-AFRICA",
	"REG-EUROPE-CENTRAL-ASIA": "REG-EUROPE-CENTRAL-ASIA",
	"REG-LATAM-CARIBBEAN": "REG-LATAM-CARIBBEAN",
	"REG-WESTERN-CENTRAL-AFRICA": "REG-WESTERN-CENTRAL-AFRICA",
	"SREG-CARIB-ENGLISH-DUTCH": "SREG-CARIB-ENGLISH-DUTCH",
	"SREG-PACIFIC-ISLANDS": "SREG-PACIFIC-ISLANDS",
	"WW": "WW"
	"": "",
},
```

There are activities which are not using proper codes in recipient-region as well as recipient-country. 

### Case 1: Invalid code in recipient-country

In http://open.undg.org/q.xml?aid=41119-CORE-PROGRAMME

![image](https://user-images.githubusercontent.com/120488/34286638-f30167f6-e709-11e7-94ac-3659edddeb9d.png)

it's using improper code in recipient-country and this will be moved to [Global-Regional](http://open.undg.org/ctrack.html?country=global-regional&tongue=eng#view=main) page

### Case 2: Invalid code in recipient-country and valid code in recipient-region

http://open.undg.org/q.xml?aid=41120-2431

![image](https://user-images.githubusercontent.com/120488/34286680-4753c0ce-e70a-11e7-8325-2babb0a002a7.png)

recipient-country code="WW" -> mapped to Global Regional
recipient-region code="998" -> mapped to [Developing Countries](http://iatistandard.org/201/codelists/Region/)

**Comment by bezunakarmi** [comment]
We have separated regions from Regional and global data. Currently only 3 regions have been identified. They are
-  89: Europe, regional
-  889: Oceania, regional
-  679: South Asia, regional

We have added them to the bottom of the current list on homepage. You can have a look at it here http://undg.staging.yipl.com.np/

**Comment by anjesh** [comment]
Is it possible to move "GR - Regional and Global" at the very bottom of the country-region listing?

![image](https://user-images.githubusercontent.com/120488/34478580-c86b3990-efc9-11e7-9726-64dd00637835.png)

**Comment by anjesh** [comment]
Also the current icon for region is blurred. Lets try to identify the good looking cc-licenced icons.

**Comment by bezunakarmi** [comment]
"GR - Regional and Global" has been moved at the of the country-region listing. Also, the icon for regional has been changed. You can check it on http://undg.staging.yipl.com.np.
