### ISSUE TITLE
UNDG IATI Dashboard

### ISSUE THREAD

**Issue by anjesh** [younginnovations/UN-Transparency-Portal#182]
IATI Dashboard is a simple platform to manage/track the issue log where we can involve the UN agencies to register and monitor the issues. The idea is to provide a common platform where UN agency focal points can create entries for identified issues and discuss the solutions.

**Comment by bezunakarmi** [comment]
@forsythej about the IATI dashboard, we could use the [Github's API](https://developer.github.com/v3/). We will have a separate interface in the portal, where the user can login from their GitHub account and can create/close/reply issue through Github's API.

Or, we can manage/create users from the portal and use the Github's API to create/close/reply issue.

**Comment by forsythej** [comment]
I would like to keep things all on the portal as Github can be confusing and also the casual user of the portal can see the dashboard.

**Comment by anjesh** [comment]
Would you have a look at http://undg-tracker.staging.yipl.com.np/auth/login 

We are making few updates here and there but it looks good for feedback from you.

**Comment by forsythej** [comment]
It looks really nice. I did speak with Gina on this and we can ditch the user registration and log-in. You can proceed with uploading it once your updates are complete.

**Comment by anjesh** [comment]
deployed at open.undg.org/issues
