### ISSUE TITLE
Add MPTF as 19th Agency

### ISSUE THREAD

**Issue by forsythej** [younginnovations/UN-Transparency-Portal#186]
Hi folks, the UN Multi Partner Trust Fund Office has now begun reporting to IATI. Their information is up on D-Portal under UN Pooled Funds (XI-IATI-UNPF). Would you kindly integrate it into Open UNDG? Many thanks.

**Comment by anjesh** [comment]
https://www.iatiregistry.org/publisher/unpf says "UN Pooled Funds". @forsythej what name should we list in UNDG portal? Also we need icon for the pooled fund for listing and for showing in the agency page. Is there any specific icon/logo for the pooled fund?

For now, we will use generic UN icon https://commons.wikimedia.org/wiki/File:UN_emblem_blue.svg for the pooled funds and use the name "UN Pooled Funds" in the staging site.

**Comment by forsythej** [comment]
For both the name and logo I agree with using the generic logo and UN Pooled Funds.

**Comment by bezunakarmi** [comment]
@forsythej UN pooled fund has been added as an un agencies in the portal. You can view it on
http://undg.staging.yipl.com.np/ctrack.html?publisher=XI-IATI-UNPF&tongue=eng#view=publisher

also on

http://open.undg.org/ctrack.html?publisher=XI-IATI-UNPF&tongue=eng#view=publisher
