### ISSUE TITLE
Add OCHA FTS to the list of agencies

### ISSUE THREAD

**Issue by anjesh** [younginnovations/UN-Transparency-Portal#188]
https://www.iatiregistry.org/publisher/ocha_fts should also be included in the list. 

Name: United Nations OCHA Financial Tracking Service
Logo: https://fts.unocha.org/sites/all/themes/custom/fts_public_v2/logo.png

@forsythej confirm if we use the above logo or different one?

**Comment by forsythej** [comment]
That logo works for me.

**Comment by bezunakarmi** [comment]
This has been implemented.
http://open.undg.org/ctrack.html?publisher=XM-OCHA-FTS&tongue=eng#view=publisher

![image](https://user-images.githubusercontent.com/12218329/34858732-0786b50c-f77a-11e7-919e-d7790d57acff.png)

![image](https://user-images.githubusercontent.com/12218329/34858747-259f90fe-f77a-11e7-922b-735473408f2d.png)
