### ISSUE TITLE
Portal is pulling zero data

### ISSUE THREAD

**Issue by forsythej** [younginnovations/UN-Transparency-Portal#194]
Hello @anjesh . The portal appears to be glitched and pulling zero information. The D Portal is operational so this must be an issue with our site.

http://open.undg.org/

**Comment by bezunakarmi** [comment]
@forsythej we have corrected the numbers in the portal. We are making some improvements to the cron task which updates the data in the portal on daily basis. Due to this, the data got little scrambled. We'll not have this issue once we finalized the cron improvements.
