### ISSUE TITLE
Home page updates

### ISSUE THREAD

**Issue by anjesh** [younginnovations/UN-Transparency-Portal#197]
## Why

* improve the look and feel of the page

## What

- [x] the top three will be totals of 1) Active Projects 2) UN Budget 3) UN Expenditure
- [x] The bottom left will be a splicer with the years 2018, 2017, 2016 and 2015. The page should be defaulted to 2018.
- [ ] The other two boxes can be the existing country box that show where the UN operates and then a box that lists the number of sectors the UN operates in, which will also be linked to the year.
- [ ] text "20 UN Publishers in IATI" to be added in between the logo and buttons
- [x] Remove the un agency logos
- [x] remove the list of countries and sectors
- [x] keep the blue compare buttons and the search tabs. Add a search tab for agencies under the corresponding ‘Compare Agencies’ tab.

![image](https://user-images.githubusercontent.com/120488/36012307-5acde638-0d85-11e8-802f-31aaeb4155a7.png)

## Notes

Notes from @forsythej 

The first thing you see when opening the page is text behind a photo, and it’s difficult to read the text depending on the picture that loads in. To get to the first visuals, you have to scroll down. My first change is to remove the subtext and ‘Learn More’ button, take the top line ‘Explore how the UNDG is contributing to the global development agenda’ and shrink it so it fits on one center-aligned line. This is done in order to move the boxes up so they are all displayed once the page loads, without the use of scrolling. For the boxes, the top three will display totals of 1) Active Projects 2) UN Budget 3) UN Expenditure. The bottom left will be a splicer with the years 2018, 2017, 2016 and 2015. The page should be defaulted to 2018. If a user selects a different year, the data shown above should shift to data from the projects that ENDED in that year. The other two boxes can be the existing country box that show where the UN operates and then a box that lists the number of sectors the UN operates in, which will also be linked to the year.

For the page header, I want to leave it mostly the same but want the number of UN publishers listed added in between the logo and buttons. The text should say simply “20 UN Publishers in IATI.
The list of countries and sectors can be removed. I’m not a fan of scrollable lists on a page that is scrollable as well. We keep the blue compare buttons and the search tabs. Add a search tab for agencies under the corresponding ‘Compare Agencies’ tab.

Remove the logos. I know that’s a big change but I don’t the idea of someone clicking through searching for a logo when they could type or click on the search tab.

Leave the SDG logos and the blue box at the bottom of the page.

**Comment by bezunakarmi** [comment]
@forsythej "The bottom left will be a splicer with the years 2018, 2017, 2016 and 2015. "

By splicer do you mean that we will have a year dropdown or a year range slider on home page.

**Comment by forsythej** [comment]
@bezunakarmi Year dropdown menu works.

**Comment by forsythej** [comment]
Hey @bezunakarmi, can I get a status update on this issue? When do you think I'll be able to see either a mock up or a finished product?

**Comment by bezunakarmi** [comment]
@forsythej we are consulting with our designing team for a mockup. We might be able to send you some mock-ups by next week. Currently, we are working on the IATI dashboard (Issue Tracker).

**Comment by forsythej** [comment]
@bezunakarmi I'd really appreciate seeing something next week so I can update the team here on progress. Have a good weekend.

**Comment by bezunakarmi** [comment]
@forsythej here is the mockup that we have prepared. Please do let us know about your feedback.

![screencapture-open-undg-org-1520498376506](https://user-images.githubusercontent.com/12218329/37142878-781eed88-22e1-11e8-8d04-121eb1e84956.png)

**Comment by bezunakarmi** [comment]
@forsythej  the new design has been updated on staging server. You can view it on http://undg.staging.yipl.com.np/

Please let us know your feedback.

**Comment by forsythej** [comment]
@bezunakarmi This is a very nice update and aligns closely with my initial request. A few requested changes:

1) Enlarge the 'Explore how the UNDG is contributing...' font so that it aligns with the boxes.
2) The font size for the top middle and top right boxes (expenditure and budget) is small when I view the page on the staging site. It looks fine on the screenshot in the above comment. 
3) There's no 'All Years' option in the year filter. Add that please.
4) In the top left box, active projects only.
5) Remove the circle graph from the expenditure box (top right)

**Comment by bezunakarmi** [comment]
@forsythej the changes have been implemented.

**Comment by forsythej** [comment]
Thank you @bezunakarmi 

One additional detail that I omitted and was brought to my attention in the office. We want to add the search boxes, which are below the compare buttons on the current home page, to the staging page. Also please add an additional search box for all the existing agencies.

We also want the search boxes to sit above the compare buttons.

**Comment by bezunakarmi** [comment]
@forsythej changes have been implemented as requested.

**Comment by anjesh** [comment]
Further updates are tracked here https://github.com/younginnovations/UN-Transparency-Portal/issues/213
