### ISSUE TITLE
Query on Sector detail page content

### ISSUE THREAD

**Issue by anjhero** [younginnovations/UN-Transparency-Portal#20]
Currently, the only way to navigate to sector detail is through tabular listing of the projects. The sector detail page only shows a list of projects (related to that sector). Do we also need to show summary stats (as in organisation detail and agency detail pages) here?

**Comment by anjesh** [comment]
As per discussion with UNDG, we will need to show summary stats here. @abdulriza to get back with more details.

**Comment by abdulriza** [comment]
@anjesh As we discussed it would be good to duplicate the same navigation as countries. The sector list will be shown in the home page and once a sector is clicked it will take to a page where we will have  a similar visualization to show all UN agencies' contribution towards that sector (where does the money come from). We will have to just take out the part - 'where does the money go' and leave the rest as it is. 

Would this be something feasible?

**Comment by abdulriza** [comment]
@anjhero @anjesh We need to re-visit the sector list on the home page. We may have to limit the sectors to OECD vocabulary only.

**Comment by anjhero** [comment]
We're working on sector detail page right now. Right now we're displaying all of the sectors. However we'll limit them to OECD vocabulary in Sprint 3.

**Comment by anjhero** [comment]
I'm closing this issue. The issue of limiting the sector list to OECD vocabulary is here: https://github.com/younginnovations/UN-Transparency-Portal/issues/51
