### ISSUE TITLE
UN-Habitat is showing 0

### ISSUE THREAD

**Issue by anjesh** [younginnovations/UN-Transparency-Portal#201]
http://open.undg.org/ctrack.html?&publisher=41120#view=publisher

![image](https://user-images.githubusercontent.com/120488/36012771-868932a2-0d88-11e8-96a0-39eee4611945.png)

[D-portal](http://d-portal.org/ctrack.html?search&publisher=41120#view=main) is showing proper data

**Comment by bezunakarmi** [comment]
Data has been updated.
