### ISSUE TITLE
Updates in Country page

### ISSUE THREAD

**Issue by anjesh** [younginnovations/UN-Transparency-Portal#209]
- [x] Add an ‘All Years’ option to the year filter
- [x] in blue box below, 'How the data is calculated' box lists dates as 2015. Update the text to current year.
- [x] Carry the filter over when a user clicks on the ‘Projects’, ‘total budget’, or ‘total expenditure’ box. 
- [x] Increase size of font of ‘About this data’ and ‘About data quality’
- [x] Increase size of Flag (within the existing space available)
- [x] The labels of agencies in the pie chart are not all displaying (see below)
![image](https://user-images.githubusercontent.com/120488/39619452-997f5600-4fa7-11e8-9f5e-d42a10f4a1a0.png)
- [x] The box on the map which lists ‘% of activities have provided exact locations. View all’ is wrong. Review how that number is queried and update. See 237% below
![image](https://user-images.githubusercontent.com/120488/39619496-c8d1dbc6-4fa7-11e8-883d-1429f7215b26.png)

**Comment by manibibek** [comment]
@anjesh the changes has been deployed to the staging server
