### ISSUE TITLE
Updates in homepage

### ISSUE THREAD

**Issue by anjesh** [younginnovations/UN-Transparency-Portal#213]
- [x] The Active Projects box and the Total Expenses box do not aggregate to All Year. It shows NA in some selections like all years, 2013
![image](https://user-images.githubusercontent.com/120488/39620067-9df9c7fe-4fa9-11e8-8a27-9d5f6b75e986.png)
- [x] change from ‘Showing data of’ to ‘Year’ in year filter
- [x]  Increase size of text and filter for year filter
- [x] UN Publishers box should display only UN agencies, and be out of a total of 40.
- [x] Change text "UN publishers in IATI" to "Publishers within the UNDG"
![image](https://user-images.githubusercontent.com/120488/39620135-e309ba0c-4fa9-11e8-81ed-e50671e79a98.png)
- [x] In dropdown Country box: Remove "recipient" from "Search for a recipient country"
- [x] In dropdown Agency box: Remove "publisher" from "Search for a UN publisher"
- [x] In dropdown Sector box: Only lists partial number of sectors, not full 5 DAC code sectors. Show all 5 digit DAC code sectors. 
- [x] Remove all the Hover Text for now. Those needs to be updated later

**Comment by bezunakarmi** [comment]
the changes has been pushed to staging server.
http://undg.staging.yipl.com.np
