### ISSUE TITLE
ILO Data not displaying

### ISSUE THREAD

**Issue by forsythej** [younginnovations/UN-Transparency-Portal#221]
Hi all,

ILO just did a major upload to IATI on 30 May. It is properly displaying on D Portal but not on the open portal. Could you have a look?

http://open.undg.org/ctrack.html?publisher=XM-DAC-41302&tongue=eng&year=2018#view=publisher

http://www.d-portal.org/ctrack.html?search&publisher=XM-DAC-41302#view=main

Thanks!

**Comment by bezunakarmi** [comment]
@forsythej the data is showing correctly. Currently, in our portal year 2018  is selected, therefore you can see few projects. If we select all year from the dropdown list, dportal and our portal stats match.

I'm closing this issue for now. You can reopen it if there's anything else.
