### ISSUE TITLE
The portal is not working for IE web browser

### ISSUE THREAD

**Issue by forsythej** [younginnovations/UN-Transparency-Portal#228]
Can the team look into the reason why the portal does not function when using Internet Explorer?

Thanks,
Jesse

**Comment by forsythej** [comment]
![ie not working](https://user-images.githubusercontent.com/33524125/45891250-15e56f00-bd93-11e8-80a5-d4e65f7b7ef6.png)

**Comment by anjesh** [comment]
Fixed. Please check and reopen if any issue @forsythej 

cc @bezunakarmi

**Comment by forsythej** [comment]
![ie error](https://user-images.githubusercontent.com/33524125/46414073-55e01680-c6f0-11e8-8fc2-729c6bfb0516.JPG)

There's still a bug. Please take another look.

Jesse

**Comment by bezunakarmi** [comment]
The new version of javascript (es6) isn't supported by older versions of Internet Explorer ( lower than v.11 and edge). We have fixed this issue and tested it with versions 9, 10, 11 and Edge. However, IE version lower than 9 have some CSS issues. Which version are you using currently? I think IE version lower than 9 isn't further supported by Microsoft as well.

**Comment by bezunakarmi** [comment]
The new version of javascript (es6) isn't supported by older versions of Internet Explorer ( lower than v.11 and edge). We have fixed this issue and tested it with versions 9, 10, 11 and Edge. However, IE version lower than 9 have some CSS issues. Which version are you using currently? I think IE version lower than 9 isn't further supported by Microsoft as well.
