### ISSUE TITLE
Sustainable Development Goals section in Homepage

### ISSUE THREAD

**Issue by anjhero** [younginnovations/UN-Transparency-Portal#34]
Make this section similar to the one as in http://undg.org.

**Comment by abdulriza** [comment]
@anjhero the page show only sustainable development and the word 'goals' is missing. Also make the goal icons bigger to match the width of above contents.

**Comment by anjhero** [comment]
We've made it same as in http://undg.org and made the icons larger so the width matches the other contents.  Please check.
