### ISSUE TITLE
List of available UN agencies in d-portal

### ISSUE THREAD

**Issue by anjesh** [younginnovations/UN-Transparency-Portal#39]
Please confirm the number of UN agencies in the d-portal. We found 12 of them - which will be used for the data analysis. @abdulriza 

![image](https://cloud.githubusercontent.com/assets/120488/13803713/fc97aa98-eb6e-11e5-8440-7941defeba4a.png)

**Comment by abdulriza** [comment]
@anjesh We need to add World Bank to the list

**Comment by anjesh** [comment]
So far there are 13 agencies to be listed in UN Portal.
