### ISSUE TITLE
Setup Icons/ Logos of all UN agencies in homepage

### ISSUE THREAD

**Issue by anjhero** [younginnovations/UN-Transparency-Portal#4]
Setup icons/ logos of all UN agencies to be used while homepage deployment.

**Comment by anjesh** [comment]
All the logos will be linked to the pages in our portal, from there, we will have links to their transparency portals (if available) and their websites. There will be pages for the agencies even if they don't have any activities in our portal. @abdulriza to come back with feedbacks.

**Comment by anjhero** [comment]
The UN agencies section in homepage should be displayed as follows:
- The UN organizations that are publishing through IATI will be the first ones to be displayed. The order to display the logos will be arranged by volume. 
- The UNDG members and observers that don’t have data will be still placed on the home page but as a watermark. 
- Place an ALT message to be displayed on the images of the agencies that don’t have data to explain that data related to the agency/fund/programme is not available yet.

**Comment by anjesh** [comment]
Logso here https://drive.google.com/a/yipl.com.np/folderview?id=0BwoAm3ycE5n2Y2RyTXRuTUJoOWs&usp=sharing#

**Comment by anjhero** [comment]
We've missed unssc's logo. Please include it @puzzz21
