### ISSUE TITLE
Do we need to include CRS data as well?

### ISSUE THREAD

**Issue by anjhero** [younginnovations/UN-Transparency-Portal#41]

**Comment by abdulriza** [comment]
@anjhero Is CRS data included in existing IATI d-portal?

**Comment by anjhero** [comment]
@abdulriza Yes, CRS data is present in existing d-portal.

**Comment by anjesh** [comment]
You may see CRS data http://d-portal.org/ctrack.html?country=BT&tongue=eng#view=donors and http://d-portal.org/ctrack.html?country=BT&tongue=eng#view=sectors

**Comment by anjesh** [comment]
CRS data to be ignored for now as we have now as per Mar 28 meeting. We will think about it later after the internal discussion at UNDG. Closing this for now.
