### ISSUE TITLE
Countries with missing flags

### ISSUE THREAD

**Issue by anjhero** [younginnovations/UN-Transparency-Portal#42]
The flags of following countries are missing. Some entries are not countries (Global Projects, Multiple, Worldwide)
- Aruba
- Bahamas
- Bahrain
- Barbados
- Belgium
- British Virgin Islands
- Bulgaria
- Congo, D.R.
- Croatia
- Curacao
- Cyprus
- Global Projects ??
- Greece
- Hungary
- Ireland
- Israel
- Italy
- Japan
- Kuwait
- Lithuania
- Multiple ??
- Oman
- Qatar
- Republic of Korea
- Romania
- Russian Federation
- Saudi Arabia
- Sint Maarten
- Slovakia
- Spain
- Sweden
- Trinidad and Tobago
- United Arab Emirates
- United States of America
- Western Sahara
- Worldwide ??

**Comment by abdulriza** [comment]
@anjhero I guess countries are picked from 'recipient-country' in IATI standards. If the activity in tagged for global (worldwide) they will not appear in any of the country and we apply the same to regional projects.
