### ISSUE TITLE
Include data portal links only for organisations and countries with data portal websites

### ISSUE THREAD

**Issue by anjhero** [younginnovations/UN-Transparency-Portal#43]
Remove the dummy content - "For more details, please visit [open.unicef.org](http://open.unicef.org/)[  
]()" for all except unicef and replace it with the actual data portal web links. For UN agencies with no data portal links, remove them.

**Comment by abdulriza** [comment]
@anjhero following are the links for UN organizations which are already having transparency portals;

undp - open.undp.org
unicef - open.unicef.org
unfpa - unfpa.org/transparency-portal
unops - data.unops.org
unesco - opendata.unesco.org

We will get back to you with other organizations links soon.

**Comment by abdulriza** [comment]
@anjhero missed 2 organizations in my previous comment;

un-habitat - open.unhabitat.org
World bank - worldbank.org/projects

**Comment by anjhero** [comment]
Thanks for these. We'll update in the site accordingly.

**Comment by anjhero** [comment]
We've updated the system with above mentioned links.
