### ISSUE TITLE
Feedback on design 

### ISSUE THREAD

**Issue by mariablancolora** [younginnovations/UN-Transparency-Portal#49]
@anjesh @anjhero
Second box: Total UN budget
Text in boxes: Just capitalize first letter of the title and the acronyms.
Big box: change title to: Trend of UN activities published in IATI
Logos: They should be displayed in the same way they are currently displayed in the UNDG site; Six logos should be displayed together.
Organization pages: Take the acronym of the organization from the title. Include the logo on the header of the page.

**Comment by anjhero** [comment]
The first 3 issues mentioned above have been addressed. Please check.

**Comment by mariablancolora** [comment]
Thanks @anjesh @anjhero 

See some more comments from today's conference:

- Also, please don't capitalize the words that are not at the beginning of the sentence and the acronyms.
- Could we try to have the logos in the same size? At least one size for the landscape ones and another size for the portrait ones. 
- Country page: Try to be consistent so we either have the name of the agency or the acronym. 
- UNDG members and observers: The title should be clickable and it should be open the page of a new tab. 
- All external links should be opened in new tabs.
-

**Comment by bezunakarmi** [comment]
@anjhero this has been done.
