### ISSUE TITLE
Theming of project detail pages

### ISSUE THREAD

**Issue by anjhero** [younginnovations/UN-Transparency-Portal#52]
We need to check each element that might appear in a project detail page and make sure the information don't get hidden as in here: http://untransparency.yipl.com.np:8082/ctrack.html?tongue=eng#view=act&aid=46004-43157-013-LN2569

**Comment by anjhero** [comment]
Where do we stand on this? @Neev89

**Comment by anjhero** [comment]
Add separator lines for each row in elements that are displayed as table. @Neev89

**Comment by bezunakarmi** [comment]
@anjhero this has been done.
