### ISSUE TITLE
Homepage re-design changes

### ISSUE THREAD

**Issue by bezunakarmi** [younginnovations/UN-Transparency-Portal#71]
- change logo as in undg.org
- blue header with white fonts
- change color for view stats section
- UN agencies stat section move total un agencies to bar chart

**Comment by anjhero** [comment]
Hi @abdulriza , we've made some design changes on the homepage. Please take a look:

![homepage](https://cloud.githubusercontent.com/assets/528549/14527454/e275ace8-0269-11e6-9065-6f809428e17b.png)

**Comment by abdulriza** [comment]
@anjhero Perfect! This looks really good. Could we try changing the color (other than blue) for view stats section? Just having a feeling that the site is overwhelmed with blue and want to see how it would look with another contrast clolor. Otherwise I am happy with the changes.

**Comment by abdulriza** [comment]
@anjhero In fact can you push the changes so that I can also try few colors myself to see how the new design would look like with a different color. Thanks.

**Comment by anjesh** [comment]
We are to push the changes with the given photo for now. Riza will try with few colors and suggest us with his thoughts. In the meantime we will also explore different colors to see what looks good to make the page a little more vibrant. 

Also there is a possibility of having video instead of a photo. For that Riza will discuss with the team and get back to us. 

Also @mariablancolora will provide us couple of pictures to choose for the homepage.

**Comment by bezunakarmi** [comment]
We have updated the homepage with new design. Please check @abdulriza

**Comment by abdulriza** [comment]
@anjesh @bezunakarmi Looks good. Can you change the introduction text to;

‘Explore how UNDG is contributing to the global development agenda.
This portal displays data from UNDG members that are currently publishing to the IATI standard’

For background, we will not have a video, instead let's try a slideshow with the pictures provided by Maria https://github.com/younginnovations/UN-Transparency-Portal/issues/86

**Comment by mariablancolora** [comment]
Great! Thanks!!

**Comment by abdulriza** [comment]
@anjesh @bezunakarmi Thanks for deploying the slideshow. Looks great but the change of pictures looks bit too fast. Can we delay it for 1 more second and make the transition little more slower.

**Comment by mariablancolora** [comment]
Hi! Could we crop the photos in a way that we show the people in the background? Also, maybe the rice collector is not the best one to include now I see it displayed. Apologies for this. 
Thanks!!

**Comment by anjhero** [comment]
@abdulriza Sure, we will make the transition slower.

@mariablancolora We'll remove the rice collector picture. And we'll see what we can we do about the cropping off photos.
