### ISSUE TITLE
Projects listing

### ISSUE THREAD

**Issue by bezunakarmi** [younginnovations/UN-Transparency-Portal#73]
- check if project end date is actual end date or planned end date.
- change links to respective pages in project listing and sector listing

**Comment by bezunakarmi** [comment]
In project listing Actual date has been given first preference, however if actual date is not present, planned date is taken.

**Comment by anjhero** [comment]
Please check @abdulriza

**Comment by abdulriza** [comment]
@anjhero @bezunakarmi I guess we are talking about the 'recently ended project listing'. I checked and it still takes the planned end date.  
Eg.http://untransparency.yipl.com.np:8082/ctrack.html?publisher=XM-DAC-41114&tongue=eng#view=publisher
if you are taking actual end date, For UNDP it shouldn't show any current month date as project end date.

**Comment by bezunakarmi** [comment]
@abdulriza  As I mentioned earlier, the "recently ended projects" section will take planned-end date if there is no actual-end date mentioned in a project. There is no actual end date mentioned for the projects that you have mentioned. Therefore the system is taking the planned end date instead, as we have verified in the xml file provided by IATI.

**Comment by bezunakarmi** [comment]
Hi @abdulriza have you checked this issue lately. Is it ok if we close this issue.

**Comment by abdulriza** [comment]
@bezunakarmi I want to discuss it on Wednesday. Lets close after the discussion.
