### ISSUE TITLE
Implementing bargraph replacing pie chart in country, organization and sector detail page

### ISSUE THREAD

**Issue by aayushrijal** [younginnovations/UN-Transparency-Portal#77]

**Comment by aayushrijal** [comment]
@abdulriza Please check the country, organization and sector detail pages and please review the bar graph that lists out all the detail.
Screenshot for the preview: 
![intp-bargraph-screenshot](https://cloud.githubusercontent.com/assets/4269966/14560830/e12f7a30-0331-11e6-9ca8-938544ae16f7.png)
[untp-bargraph.mov.zip](https://github.com/younginnovations/UN-Transparency-Portal/files/220901/untp-bargraph.mov.zip)

**Comment by anjesh** [comment]
As per skype today (apr 15), the country page and sector page should show the % of the un agencies under "where does the money come from?". It means that it should be pie chart or something similar that clearly reflects the proportion of these agencies. 

However first we will deploy the bar charts for all blocks for now and later Riza will discuss with the team and get back to us with their feedbacks.

**Comment by bezunakarmi** [comment]
The changes has been deployed for barcharts in country, agency and sector pages. Please do check @abdulriza

**Comment by abdulriza** [comment]
@bezunakarmi @anjesh Thanks. While we wait for the pie chart presentation for country pages, I can confirm that we are good with bar charts for other pages. Could you bring in the % also on the bar charts (may be in the front) to show the % as well with the amount?

**Comment by anjhero** [comment]
Sure. We'll implement this.

**Comment by abdulriza** [comment]
@anjhero The country pie chart design is still pending.

**Comment by anjhero** [comment]
Hi @abdulriza, 
We've worked on the "Where does the money come from?" section of the country detail page. Please take a look:

We've tried two options:
1. Scatter graph
The first one is the scatter graph. The agencies are shown in x-axis and the budget amount is represented by y-axis. The size of the bubble also determines the share of the budget of a given agency in the country. Here's the graph:
![country detail - scatter](https://cloud.githubusercontent.com/assets/528549/15639813/2cec4656-2650-11e6-9cc0-d4bd8f86f11d.png)

2. Pie charts
The second one is the pie chart (similar to the one in D-portal). The one in the D-portal had lines coming out of the pies to refer to the respective agencies. We've removed the lines as they seemed pretty confusing. We've added shares of each agency as separate pies for a better, detailed and neat representation of the data. Please take a look:
![country detail - pie chart](https://cloud.githubusercontent.com/assets/528549/15639871/2067e31c-2651-11e6-83be-f90995561ae8.png)

The pies on hover also show percentage share, agency name and budget amount:
![country detail - piechart-hover](https://cloud.githubusercontent.com/assets/528549/15639884/4914c528-2651-11e6-98f5-07069d8c62a4.png)

Looking forward to hear from you on this.

**Comment by abdulriza** [comment]
@anjhero Thanks for this. I like the second option. But let me get back to you tomorrow after discuss this with the team.

**Comment by abdulriza** [comment]
@anjhero We are happy with the pie chart option and you can go ahead with it. I have couple of questions which we can discuss when we talk later.

**Comment by aayushrijal** [comment]
Hello @abdulriza ,
The percentage value in the pie chart had been fluctuating with 1% and was showing inconsistent value when summed up, due to rounding off of the value. So we had the decimal value shown in the pie chart which is more consistent now and sums up to 100%
Also the smaller pie charts are vertically scroll-able when the charts are more than six.  Please do check and notify us if any changes are to be made. http://open.undg.org/ctrack.html?country=AF&tongue=eng#view=main

**Comment by abdulriza** [comment]
@aayushrijal  Looks great now. On making the acronyms for the pie chart, I noticed you are using UNWFP for United Nations World Food programme. Please change it to WFP. When we use the acronym we use WFP, not UNWFP.  

Also I notice in the table http://open.undg.org/ctrack.html?country=AF&tongue=eng#view=donors you are using acronyms UNH for UN-Habitat, UNWFP for United Nations World Food programme and UNPF for UN population fund. They also need to be changed as follows;

- UN-Habitat : UN-Habitat is in fact the acronym for United Nations Human Settlement Programme. Therefore, do not use UNH as acronym, instead use UN-Habitat everywhere.
- United Nations Population Fund : UNFPA (not UNPF)
- United Nations World Food programme : WFP (not UNWFP)

**Comment by abdulriza** [comment]
@aayushrijal Also just noticed that sector pages are not showing the acronyms instead the cut-off full names http://open.undg.org/ctrack.html?sector_group=311&tongue=eng#view=sector. It looks like the change was made only to country page. Please fix it for sector pages as well.

**Comment by bezunakarmi** [comment]
This has been done.
![screen shot 2017-02-21 at 10 11 16 am](https://cloud.githubusercontent.com/assets/12218329/23150756/1ee53d74-f81e-11e6-85e9-19ba18359fb8.png)
