### ISSUE TITLE
Updates in sector list and sector page

### ISSUE THREAD

**Issue by anjesh** [younginnovations/UN-Transparency-Portal#79]
3 digit sector codes should be used while listing in the homepage. All the 5 digits sector code should be mapped to 3-digit codes.

While viewing the sector page, it should show the aggregation of all the 5 digit sectors (+ that particular 3 digit sector if it exists) that belong to that 3 digit sector. 

And the 5 digit sectors should be listed in the bar or pie chart under "Where does the money go to?" block.

**Comment by anjhero** [comment]
This has been implemented. Please check @anjesh @abdulriza 

The 5-digit sector section in 3-digit sector page needs to be themed as in other sections of the same nature. @Neev89
