### ISSUE TITLE
Verify the project data

### ISSUE THREAD

**Issue by anjesh** [younginnovations/UN-Transparency-Portal#80]
http://untransparency.yipl.com.np:8082/ctrack.html?&publisher=XM-DAC-41114#view=act&aid=XM-DAC-41114-OUTPUT-00095585 shows different end date from the same project in d-portal http://d-portal.org/ctrack.html?&publisher=XM-DAC-41114#view=act&aid=XM-DAC-41114-OUTPUT-00095585

![image](https://cloud.githubusercontent.com/assets/120488/14585106/57659f44-0487-11e6-86fb-63bf87156d0f.png)

![image](https://cloud.githubusercontent.com/assets/120488/14585108/6501e892-0487-11e6-9e85-7b828429df23.png)

Hence the project listing http://untransparency.yipl.com.np:8082/ctrack.html?&publisher=XM-DAC-41114#view=publisher showing the end dates are also not correct

**Comment by bezunakarmi** [comment]
this has been done.
