### ISSUE TITLE
Photos on homepage

### ISSUE THREAD

**Issue by mariablancolora** [younginnovations/UN-Transparency-Portal#86]
Here are some links to great photos that we could use:

http://www.unmultimedia.org/photo/detail.jsp?id=397/397640&key=11&query=bamyan&lang=en&sf=
http://www.unmultimedia.org/photo/detail.jsp?id=451/451902&key=1&query=urbanization&lang=en&sf=
http://www.unmultimedia.org/photo/detail.jsp?id=553/553610&key=3&query=subject:%22International%20Day%20of%20Happiness%22&lang=en&sf=date
http://www.unmultimedia.org/photo/detail.jsp?id=533/533053&key=4&query=subject:%22International%20Day%20of%20Happiness%22&lang=en&sf=date
http://www.unmultimedia.org/photo/detail.jsp?id=199/199859&key=49&query=women&lang=en&sf=
http://www.unmultimedia.org/photo/detail.jsp?id=542/542660&key=0&query=woman&lang=en&sf=
http://www.unmultimedia.org/photo/detail.jsp?id=178/178792&key=59&query=woman&lang=en&sf=
http://www.unmultimedia.org/photo/detail.jsp?id=482/482468&key=197&query=woman&lang=en&sf=

Could we have a slide show instead of an static photo? 

@anjesh @anjhero

**Comment by anjhero** [comment]
This is implemented. I'm closing this issue.
