### ISSUE TITLE
Logo UNIDO to be changed

### ISSUE THREAD

**Issue by mariablancolora** [younginnovations/UN-Transparency-Portal#88]
Could you kindly change the logo from UNIDO on the slide show? Could you kindly use this one?

[UNIDO Logos.zip](https://github.com/younginnovations/UN-Transparency-Portal/files/228914/UNIDO.Logos.zip)

Thanks!!
@anjesh @anjhero

**Comment by anjhero** [comment]
@mariablancolora  We've used Unido_logo_light_blue.jpg from the zip file you provided. Please check

**Comment by mariablancolora** [comment]
I think is ok. I have sent it to the agency comms person to double check. Thanks!!
