### ISSUE TITLE
Feedback email 

### ISSUE THREAD

**Issue by mariablancolora** [younginnovations/UN-Transparency-Portal#89]
For the feedback section of the website, email will be sent to kit.doco@undg.org

**Comment by anjhero** [comment]
Right now, the feedback is linked to Github's issue page of this project. We're thinking of building a separate page for feedback which will include an email link and link to the Github's page. 

@bezunakarmi will follow up on this shortly.

**Comment by abdulriza** [comment]
@anjhero @bezunakarmi Let's have a separate small pop-up window open for feedback. The idea is that a viewer can instantly submit their feedback (or questions) by a simple form submission which will be linked to kit.doco@undp.org. Something similar to what we have on open.undp.org. Could you please check.

**Comment by anjhero** [comment]
Hi @abdulriza, it is a good idea to put up a pop up window for feedback. We''re working on this right now and get back to you once it is done.

**Comment by anjhero** [comment]
A pop up feedback section is implemented. As we talked with @abdulriza earlier today, the pop up box will disappear in about 2s after the user clicks on "Send message". 

@aayushrijal please follow up on this.

**Comment by anjhero** [comment]
The form fields aren't validated yet. Please check @aayushrijal

**Comment by bezunakarmi** [comment]
This has been done.
