### ISSUE TITLE
Design of agency page

### ISSUE THREAD

**Issue by mariablancolora** [younginnovations/UN-Transparency-Portal#90]
Could we make the font being used for the names of the agencies smaller? I think the logo and the font should be more proportionate. Thanks!!

**Comment by anjhero** [comment]
@mariablancolora we've decreased the font size for all titles and made the logo and the text sizes proportionate. Please check.

**Comment by mariablancolora** [comment]
Thanks @anjhero. Could you kindly make sure that the size of the logos are proportional? The logo of UNOPS is small if you compare it with UNFPA's. All of them should be included in the same size and aligned in the same way to the name of the agency. Thanks.

**Comment by anjhero** [comment]
Based on our meeting with @abdulriza earlier today, we'll change the logo size so that they match with the ones in the homepage.

@Neev89 please follow up on this.
