### ISSUE TITLE
Data validation 

### ISSUE THREAD

**Issue by abdulriza** [younginnovations/UN-Transparency-Portal#92]
@anjesh @anjhero While we are looking into the final design changes, it is time to shift our focus to data. Please let me know when we can start checking the numbers. Portal still doesn't show the correct numbers. Let's track all data related queries here.

**Comment by bezunakarmi** [comment]
@abdulriza we are writing a script to fetch data from IATI but as few agencies data are too large to download in a single file, we are trying to fetch the data by breaking it in chunks so it can be easily dowloaded/implememted in the system. So we will get to you on the data as soon as possible.

**Comment by abdulriza** [comment]
@bezunakarmi @anjesh Thanks. I am now bit concerned as the data download process is taking much longer than it should be. I would appreciate if you could prioritize and get it done sooner. I would also like to know more about the issue. Since the existing portal is also fetching the data from IATI registry and we kind of can use the same script without any issues right? May be I am missing something. Let me know if you like to have a quick call to discuss later this week.

**Comment by bezunakarmi** [comment]
@abdulriza we have downloaded and processed the data required for the system. It has been implemented on our test server. In d-portal it uses countries xml for data presentation, where as in our system we are fetching UN-Agencies xml for data. So our problem was downloading a large size xml file and processing it. In our case UNICEF's xml file is too large even to download and had issues while processing it using d-portal's script. So we downloaded xml in chunks of 3000 activities and process it. Download wasn't a smooth process, we had to try running the same script for multiple times to complete the download. Therefore it took lot time than we expected.
And for the issue with ordering agencies by their budget in homepage, we checked the data and found out that in UNICEF budget were of type=2 (i.e Revised Budget). In our script we only calculated the budget which was of type=1 (i.e. Original Budget). So, UNICEF is shown lower in order.
We will need to consult with the d-portal team about the issue and how to overcome it.

**Comment by abdulriza** [comment]
@bezunakarmi @anjesh Thanks. I don't think there should be any difference in fetching the data and it can be same as d-portal. Assuming that now you have downloaded all data, still the numbers are very much wrong. And for the order, not only UNICEF but other organizations are also not getting listed correctly. I don't think the script should define the budget type at all. It should calculate all the budget element despite whether it is type 1 or 2. Need to discuss urgently.

**Comment by anjhero** [comment]
@abdulriza @anjesh @bezunakarmi Lets discuss on this Wednesday morning 11:00am Nepal's time. Let me know if the timing is right for you.

**Comment by abdulriza** [comment]
@anjhero @anjesh @bezunakarmi I am good with Wednesday morning 11am Nepal time. Thanks.

**Comment by abdulriza** [comment]
@bezunakarmi @anjesh @anjhero listing down some issues we need to urgently addressed to;

- Aggregated numbers are totally messed up - let's discuss urgently

- Numbers don't match - I can confirm the numbers d-portal shows for UNDP is correct. Following is the comparison with UNDG portal and d-portal

![pic](https://cloud.githubusercontent.com/assets/3297817/15596844/d94592be-2398-11e6-9eea-df20b87ecacc.png)

- compare all countries table includes countries with all zero value. Make sure the countries with all zero values do not appear in the table
http://188.166.155.208/ctrack.html?tongue=eng#view=publisher_countries

- compare all countries table IATI budget 'total' column shows zero for all years. This information is extracted from IATI organization files. 
http://188.166.155.208/ctrack.html?tongue=eng#view=publisher_countries

- country page where does the money come from link takes to the table with all organizations instead of UN agencies only table 
http://188.166.155.208/ctrack.html?country=AF&tongue=eng#view=donors

- sector page where does the money come from link directed to a wrong all country table. it should be for the view all table with agencies

- Agency page the funding went to (view all) table includes countries with all zero value. Make sure the countries with all zero values do not appear in the table
http://188.166.155.208/ctrack.html?publisher=XM-DAC-41114&tongue=eng#view=publisher_countries

- It looks UNDG portal is dropping projects. For example, total project number for UNDP in Afghanistan should be 99 whereas undg portal is showing only 92 
http://188.166.155.208/ctrack.html?publisher=XM-DAC-41114&tongue=eng#view=list_transactions&country_code=AF
