### ISSUE TITLE
About Page - New text

### ISSUE THREAD

**Issue by mariablancolora** [younginnovations/UN-Transparency-Portal#98]
About page text

**The United Nations commitment to transparency**
The UN development system works to meet the request by the UN Economic and Social Council  through the Quadrennial Comprehensive Policy Review to strengthen the analytical quality of system-wide reporting on funding and performance and programme results for United Nations operational activities for development, including the coverage, timeliness, reliability, quality and comparability of system wide data, definitions and classifications.
 
As part of this commitment to transparency, in 2011, at the Fourth High Level Forum on Aid Effectiveness in Busan, Korea, the United Nations Development Group, endorsed the Busan Partnership for Effective Development Co-operation including a commitment to publish data according to IATI standard.  An increasing number of UNDG members and observers are now publishing data and joining the International Aid Transparency Initiative (IATI) as members.

**IATI**
IATI is a voluntary, multi-stakeholder initiative that seeks to improve the transparency of aid, development, and humanitarian resources in order to increase their effectiveness in tackling poverty. It brings together donor and recipient countries, civil society organizations, and other experts in aid information who are committed to working together to increase the transparency and openness of aid. At the center of IATI is the IATI Standard, a format and framework for publishing data on development cooperation activities, intended to be used by all organizations in development, including government donors, private sector organizations, and national and international NGOs. It was designed in close consultation with key users of development cooperation data in developing countries, to ensure its relevance and utility for a variety of different data users.[1]

**UNDG at country level**
The UNDG has approved the Standard Operating Procedures for countries adopting the delivering as one approach. These include the development of consolidated financial frameworks that are designed to increase transparency by providing governments, donors and other stakeholders with a simplified single overview of the funding situation.
 
With a view to consolidating these various efforts, the UNDG has developed this portal which draws together all the data published to IATI by UN entities. It promotes a common approach to the application of transparency standards amongst UNDG members through the publication of financial and activity data according to the IATI standard. The portal is overseen by the UNDG Data and transparency task team. 

Questions? Contact kit.doco@undg.org

**Comment by anjhero** [comment]
This has been implemented. Please check @mariablancolora
